import { consentTrial } from '../src/trials/consent';
import { labeledRatingTrial, attentionTrial, labelSentence } from '../src/trials/rating';
import { ratingStem, humanLabel, aiLabel, RATING_CHOICES, RATING_ANCHORS } from '../src/copy';
import { validateManifest } from '../src/manifest';

const m = validateManifest({ name: 'd', protocol_version: 'v0', domain_version: 'v0', wave: 1, artifact_type: 'text', evaluator_class: 'lay',
  stem_noun: 'poem', human_verb: 'written', labeled_artifacts_per_session: 2, unlabeled_per_session: 0, attention_checks: 0,
  artifacts: { human: { '0': 'a.txt' }, ai: { '0': 'b.txt' } }, curation_criteria: 'c.md', osf_study: 'x' });
const art = { id: 'd_v0_human_0', author: 'human' as const, index: 0, path: 'a.txt' };
const item = { kind: 'labeled' as const, artifact: art, stated_author: 'ai' as const, survey_pos: 3 };

test('stem uses the noun', () => { expect(ratingStem('poem')).toBe('Rate the quality of this poem on a scale of 1 to 10.'); });
test('human label uses the verb', () => { expect(humanLabel('written')).toBe('This was written by a person.'); });
test('one anchor per rating choice, and buttons show number and anchor', () => {
  expect(RATING_ANCHORS).toHaveLength(RATING_CHOICES.length);
  const t = labeledRatingTrial(item, { artifact: art, content: 'poem' }, m);
  expect(t.button_html('7', 6)).toContain('7'); expect(t.button_html('7', 6)).toContain('Somewhat high');
});
test('consent trial has the registered sentence and an agree button', () => {
  const t = consentTrial(m, true);
  expect(t.stimulus).toContain('cannot be fully described in advance'); expect(t.choices).toEqual(['I agree']);
});
test('consent states the expected length from the manifest, with minutes appended', () => {
  expect(consentTrial(m, true).stimulus).toContain('takes about 5-10 minutes');
  expect(consentTrial({ ...m, expected_minutes: '15-20' }, true).stimulus).toContain('takes about 15-20 minutes');
});
test('platform-id paragraph appears only when the session id came from the platform', () => {
  expect(consentTrial(m, true).stimulus).toContain('Your platform ID is stored separately');
  expect(consentTrial(m, false).stimulus).not.toContain('platform ID');
  expect(consentTrial(m, false).stimulus).toContain('By pressing "I agree"');
});
test('labeled trial shows the stated label, not the true author, and records plan fields', () => {
  const t = labeledRatingTrial(item, { artifact: art, content: 'poem' }, m);
  expect(t.stimulus).toContain('This was generated by an AI system.');
  expect(t.stimulus).not.toContain('by a person');
  expect(t.choices).toEqual(RATING_CHOICES);
  expect(t.stimulus).toContain('Rate the quality of this poem');
  expect(t.data).toEqual({ trial_kind: 'labeled', artifact_id: art.id, actual_author: 'human', stated_author: 'ai', survey_pos: 3 });
});
test('human-labeled trial uses the domain verb', () => {
  const t = labeledRatingTrial({ ...item, stated_author: 'human' }, { artifact: art, content: 'poem' }, m);
  expect(t.stimulus).toContain('This was written by a person.');
});
test('labels keep the registered wording without a noun, and name the noun when given one', () => {
  expect(aiLabel()).toBe('This was generated by an AI system.');
  expect(humanLabel('written', undefined)).toBe('This was written by a person.');
  expect(aiLabel('answer')).toBe('This answer was generated by an AI system.');
  expect(humanLabel('written', 'answer')).toBe('This answer was written by a person.');
});
test('label_noun is off by default, so a domain that does not set it keeps the registered labels', () => {
  expect(m.label_noun).toBe(false);
  expect(labelSentence(m, 'human')).toBe('This was written by a person.');
  expect(labelSentence(m, 'ai')).toBe('This was generated by an AI system.');
});
test('with label_noun on, both labels name the stem noun, on the page and in an image alt', () => {
  const mn = validateManifest({ ...m, stem_noun: 'answer', label_noun: true });
  expect(labelSentence(mn, 'human')).toBe('This answer was written by a person.');
  expect(labelSentence(mn, 'ai')).toBe('This answer was generated by an AI system.');
  const human = labeledRatingTrial({ ...item, stated_author: 'human' }, { artifact: art, content: 'q and a' }, mn);
  expect(human.stimulus).toContain('<p class="label">This answer was written by a person.</p>');
  const ai = labeledRatingTrial(item, { artifact: art, content: 'q and a' }, mn);
  expect(ai.stimulus).toContain('<p class="label">This answer was generated by an AI system.</p>');
  expect(ai.stimulus).toContain('Rate the quality of this answer');
  const img = validateManifest({ ...mn, artifact_type: 'image', stem_noun: 'painting', human_verb: 'painted',
    artifacts: { human: { '0': 'a.png' }, ai: { '0': 'b.png' } } });
  const imgArt = { ...art, path: 'a.png' };
  expect(labeledRatingTrial({ ...item, artifact: imgArt, stated_author: 'human' }, { artifact: imgArt, content: 'https://h.test/a.png' }, img).stimulus)
    .toContain('alt="This painting was painted by a person."');
});
test('with label_noun on, the noun is escaped in the label and the alt text', () => {
  const mn = validateManifest({ ...m, stem_noun: 'a <b>"poem"', label_noun: true });
  const t = labeledRatingTrial(item, { artifact: art, content: 'poem' }, mn);
  expect(t.stimulus).toContain('This a &lt;b&gt;&quot;poem&quot; was generated by an AI system.');
  expect(t.stimulus).not.toContain('<b>');
});
test('with label_noun on, an attention check still carries no provenance label', () => {
  const mn = validateManifest({ ...m, stem_noun: 'answer', label_noun: true });
  const t = attentionTrial({ kind: 'attention', check_index: 0, expected: 7, artifact: art }, { artifact: art, content: 'x' }, mn);
  expect(t.stimulus).not.toMatch(/by a person|AI system/);
});
test('attention trial shows a real artifact with an instruction in place of the label, and records expected value', () => {
  const t = attentionTrial({ kind: 'attention', check_index: 1, expected: 7, artifact: art }, { artifact: art, content: 'poem body' }, m);
  expect(t.stimulus).not.toMatch(/by a person|AI system/);
  expect(t.stimulus).toContain('poem body');
  expect(t.stimulus).toContain('select 7');
  expect(t.choices).toEqual(RATING_CHOICES);
  expect(t.data).toEqual({ trial_kind: 'attention', check_index: 1, expected: 7, artifact_id: art.id, actual_author: 'human' });
});
test('manifest-derived copy is escaped in the prompt, not interpolated raw', () => {
  const mUnsafe = validateManifest({ ...m, stem_noun: 'a <b>&"poem"' });
  const t = labeledRatingTrial(item, { artifact: art, content: 'poem' }, mUnsafe);
  expect(t.stimulus).toContain('a &lt;b&gt;&amp;&quot;poem&quot;');
  expect(t.stimulus).not.toContain('<b>');
});
