// Draft consent and debrief text follow ETHICS.md: authorised-deception consent that stays general;
// debrief that states labels were randomly assigned and why, and offers one-click withdrawal.
// The PI approves final wording before collection (D10).
export const COPY = {
  consentTitle: 'Consent',
  consentBody: (expectedMinutes: string) => [
    'You are invited to take part in a study on how people judge the quality of creative and professional work. You will be shown a series of items and asked to rate each one.',
    `The session takes about ${expectedMinutes} minutes. You may stop at any time by closing this window; if you stop before the end, your responses will not be used.`,
    'Some aspects of this study cannot be fully described in advance; you will be told everything at the end.',
  ],
  // Shown only when a platform session id was passed in; placed before consentClose.
  consentPlatformId: 'Your platform ID is stored separately from your ratings and is used only to pay you and to link your responses to the platform’s demographic export, which is reported in aggregate only.',
  consentClose: 'By pressing "I agree" you confirm that you are 18 or older, have read and understood this information, and agree to take part.',
  consentButton: 'I agree',
  attentionInstruction: (n: number) =>
    `This item is an attention check. Please ignore the item below and select ${n} on the scale.`,
  // Expertise screen (expert domains): one question right after consent; a wrong answer ends the session.
  prescreenIntro: 'Before you begin, one question about the item below.',
  screenOutTitle: 'Thank you',
  screenOutBody: 'This study needs participants with a particular background, and your answer did not match. Your session ends here.',
  unlabeledStatement: 'For the following, we will not tell you who made them.',
  demographicsStatement: 'We will now ask some questions about you.',
  beliefQuestion: 'Who do you think made this, a person or an AI system?',
  beliefChoices: ['A person', 'An AI system'] as const,
  debriefTitle: 'About this study',
  debriefBody: [
    'Thank you. Some of the items you rated carried a statement about who made it. Those statements were assigned at random and were not always true: some work made by a person was labelled as AI-generated, and some AI-generated work was labelled as made by a person.',
    'We did this to measure whether the same work is rated differently depending on who people believe made it. Telling you in advance would have changed how you rated.',
    'If you would prefer that your responses not be used, tick the box below before submitting.',
  ],
  // Appended to the last debrief paragraph only when a platform session id was passed in.
  debriefPaid: 'You will be paid either way.',
  withdrawLabel: 'Please withdraw my responses from this study.',
  submitButton: 'Submit',
  // Shown while the files are posted to DataPipe, which takes several seconds per file; closing the tab here loses the session.
  savingTitle: 'Saving your responses',
  savingBody: 'This can take up to a minute. Please keep this page open.',
  thanksTitle: 'Thank you',
  thanksBody: 'Your responses have been recorded. You may now close this window.',
  // Used for both the alert on submit failure and the thank-you page; the session id is appended.
  submitFailed: 'We could not save your responses. Please contact the researcher and quote this session id: ',
  thanksRedirect: 'You will be returned to the platform in a moment.',
  continueButton: 'Continue',
  // Shown over the progress bar while an image domain's artifacts download, between consent and the first rating.
  preloadMessage: 'Loading the items. This can take a moment on a slow connection.',
  startupFailed: 'This study could not be started. Please return the submission on the platform.',
};
export const RATING_CHOICES = Array.from({ length: 10 }, (_, i) => String(i + 1));
export const RATING_ANCHORS = ['Extremely low', 'Very low', 'Low', 'Somewhat low', 'Slightly low',
                               'Slightly high', 'Somewhat high', 'High', 'Very high', 'Extremely high'];
export const AI_LABEL = 'This was generated by an AI system.';
export function humanLabel(verb: string): string { return `This was ${verb} by a person.`; }
export function ratingStem(noun: string): string { return `Rate the quality of this ${noun} on a scale of 1 to 10.`; }
